VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="Middle Man Club"
ORG_URL="https://middleman.club"
ORG_LOGO="https://middleman-club.herokuapp.com/imgs/company.png"
ORG_DESCRIPTION="Description of issuer"
ORG_PHYSICAL_ADDRESS="123 Sesame Street, New York, NY 12345, United States"
ORG_PHYSICAL_ADDRESS_ATTESTATION="https://www.domain.com/address_attestation.jpg"
ORG_PHONE_NUMBER="1 (123)-456-7890"
ORG_PHONE_NUMBER_ATTESTATION="https://www.domain.com/phone_attestation.jpg"
ORG_KEYBASE="accountname"
ORG_TWITTER="orgtweet"
ORG_GITHUB="orgcode"
ORG_OFFICIAL_EMAIL="support@domain.com"

[[CURRENCIES]]
code="EDU"
issuer="GAKZMGFNOAZZP5S57JGMILKNMKVGL6465AD6QKRBD3E7JTHUCZHIEB3A"
display_decimals=8
name="Educational Coin"
image="https://middleman-club.herokuapp.com/company.png"